#
#  spring:
#    server:
#      port:8082
#
##    spring:
##      profiles:
##        active: dev
#---
#    spring:
#      profiles:dev
#      datasource
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      password: root
#      platform: mysql
#      url: jdbc:mysql://localhost:3300/project
#      username: root
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#
#      management:
#        endpoints:
#          web:
#            exposure:
#              include: "*"
#              exclude: dev, beans
#
##---
##  spring:
##    profiles:qa
##    datasource
##  datasource:
##    driver-class-name: com.mysql.cj.jdbc.Driver
##    password: root
##    platform: mysql
##    url: jdbc:mysql://localhost:3300/projectqa
##    username: root
##  jpa:
##    hibernate:
##      ddl-auto: update
##    show-sql: true
##
##---
##
##  spring:
##    profiles:prod
##    datasource
##  datasource:
##    driver-class-name: com.mysql.cj.jdbc.Driver
##    password: root
##    platform: mysql
##    url: jdbc:mysql://localhost:3300/projectproduction
##    username: root
##  jpa:
##    hibernate:
##      ddl-auto: update
##    show-sql: true
##    management:
##      endpoints:
##        web:
##          exposure:
##            include: "*"
##
#
